# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_dispatch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'event_dispatch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65vent_dispatch.proto\"\x1f\n\x0e\x46lashcardGrade\x12\r\n\x05grade\x18\x01 \x01(\x05\"h\n\x10\x46lashcardToGrade\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65\x63kName\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x04 \x01(\t\x12\x0e\n\x06userId\x18\x05 \x01(\x03\"\x95\x01\n\x13\x43\x61rdUpdateEventGRPC\x12\x12\n\nupdateType\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61rdId\x18\x02 \x01(\x03\x12\x0e\n\x06\x64\x65\x63kId\x18\x03 \x01(\x03\x12\x0e\n\x06userId\x18\x04 \x01(\x03\x12\x18\n\x10isMultipleChoice\x18\x05 \x01(\x08\x12\x10\n\x08question\x18\x06 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x07 \x03(\t\"\x8d\x01\n\x1aRecommendFeedbackEventGRPC\x12\x13\n\x0bwasAccepted\x18\x01 \x01(\x08\x12\x0e\n\x06userId\x18\x02 \x01(\x03\x12\x0e\n\x06\x64\x65\x63kId\x18\x03 \x01(\x03\x12\x10\n\x08question\x18\x04 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x05 \x03(\t\x12\x18\n\x10isMultipleChoice\x18\x06 \x01(\x08\"\xb1\x01\n\x10\x42\x61tchMessageGRPC\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x0e\n\x06\x64\x65\x63kId\x18\x02 \x01(\x03\x12\x10\n\x08\x64\x65\x63kName\x18\x03 \x01(\t\x12\x12\n\ncategories\x18\x04 \x03(\t\x12(\n\ncardUpdate\x18\x05 \x03(\x0b\x32\x14.CardUpdateEventGRPC\x12-\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x06 \x03(\x0b\x32\x1b.RecommendFeedbackEventGRPC\"G\n\x12\x44ispatchResultGRPC\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x03 \x03(\t2P\n\x0f\x45ventDispatcher\x12=\n\x13\x44ispatchCardUpdates\x12\x11.BatchMessageGRPC\x1a\x13.DispatchResultGRPC2^\n\x1a\x46lashcardToGradeDispatcher\x12@\n\x18\x44ispatchFlashcardToGrade\x12\x11.FlashcardToGrade\x1a\x0f.FlashcardGrade0\x01\x42;\n\x1b\x63om.learnd.integration.grpcB\x14\x45ventDispatcherProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_dispatch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.learnd.integration.grpcB\024EventDispatcherProtoP\001\242\002\003RTG'
  _globals['_FLASHCARDGRADE']._serialized_start=24
  _globals['_FLASHCARDGRADE']._serialized_end=55
  _globals['_FLASHCARDTOGRADE']._serialized_start=57
  _globals['_FLASHCARDTOGRADE']._serialized_end=161
  _globals['_CARDUPDATEEVENTGRPC']._serialized_start=164
  _globals['_CARDUPDATEEVENTGRPC']._serialized_end=313
  _globals['_RECOMMENDFEEDBACKEVENTGRPC']._serialized_start=316
  _globals['_RECOMMENDFEEDBACKEVENTGRPC']._serialized_end=457
  _globals['_BATCHMESSAGEGRPC']._serialized_start=460
  _globals['_BATCHMESSAGEGRPC']._serialized_end=637
  _globals['_DISPATCHRESULTGRPC']._serialized_start=639
  _globals['_DISPATCHRESULTGRPC']._serialized_end=710
  _globals['_EVENTDISPATCHER']._serialized_start=712
  _globals['_EVENTDISPATCHER']._serialized_end=792
  _globals['_FLASHCARDTOGRADEDISPATCHER']._serialized_start=794
  _globals['_FLASHCARDTOGRADEDISPATCHER']._serialized_end=888
# @@protoc_insertion_point(module_scope)
